services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres  # Referencing the network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4  # Corrected image reference
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-PGADMIN@PGADMIN.ORG}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres  # Referencing the network
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:

networks:
  postgres:  # Defined the 'postgres' network here
    driver: bridge
